### ISSUE TITLE
get data

### ISSUE THREAD

**Issue by TapsHTS** [tonylin0826/yeelight.io#1]
Hi ! Can i get a result of data ? IsOn ? The color etc... ?

**Comment by tonylin0826** [comment]
Hi @TapsHTS , you can use [this](https://github.com/tonylin0826/yeelight.io#event-data) to get response data from the yeelight

If you would like to access the bulb status, `bulb.props` should have the status stored in it.

**Comment by TapsHTS** [comment]
I use bulb.props. Thank's !

**Comment by tonylin0826** [comment]
feel free to submit MR for new features or bug fixes, thank you!

**Comment by TapsHTS** [comment]
Sorry, I have a problem @tonylin0826, when I do:
```js
const { Bulb } = require('yeelight.io');
const l1 = new Bulb('192.168.X.XX');

l1.connect();
console.log(l1.props);
```
It return
```
{}
```
It's normal ?
